apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-ad-statistics-demo
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/sbs/pam-ad-statistics-demo/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
