management:
  endpoint.health.enabled: true
  endpoints:
    prometheus.enabled: true
    prometheus.web.enabled: true
    web.exposure.include: health,info,status,metrics,prometheus,configprops,env,conditions,beans,auditevents,mappings
  metrics:
    web.server.auto-time-requests: true
    distribution.percentiles-histogram.http.server.requests: true
    distribution.percentiles-histogram.http.client.requests: true
  health:
    elasticsearch:
      enabled: false
spring:
  metrics.web.server.auto-time-requests: true
  task.scheduling.pool.size: 5
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  profiles:
    active: local

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  servlet:
    context-path: /

scheduler:
  enable: true

pagesize:
  value: 10000

date:
  start: 1DaysAgo
  end: today
